### ISSUE TITLE
Images and apt upgrade support for oled display

### ISSUE THREAD

**Issue by mjstn** [UbiquityRobotics/pi_image_build#12]
It is time to enable and make the image be able to support our MCB OLED display.

The node is written to detect if the display is present and abort if no display found so this seems enough to now ship it.

We need next image created in our 'slow cadence' to support this OLED node.
We need perhaps even before then an apt upgrade to pull it in for existing users.

We are shipping the OLED display and doing good things like showing IP and battery voltage and blink when battery voltage is low.

**Comment by MoffKalast** [comment]
For reference the package name is `ros-kinetic-oled-display-node`
