### ISSUE TITLE
Fresh magni out of production spins on firmware image boot

### ISSUE THREAD

**Issue by JanezCim** [UbiquityRobotics/pi_image_build#18]
Firmware image: 2020-04-21-firmware-load
Flashed with etcher
On other robots same image works fine: loads firmware, drivers straight then 180degrees

What is happening:
https://workdrive.zoho.com/file/p8xiae47c4e334e4f40eb8981c4d58acd5a66

Im also seeing RPI losing power every time robot stops. What could be wrong? Is it something with MCB? Have we seen this problem already? @mjstn

**Comment by mjstn** [comment]
We have to be sure we can load current revs only which include these   v40 and v43

We do not have to test firmware load on ancient stuff like 2020-04-21     OR do you mean that is the image date???

I don't see any image on our release page for that date.  https://downloads.ubiquityrobotics.com/pi.html

**Comment by mjstn** [comment]
As far as RPi loosing power we have a known issue where we have only recently been shipping mcb units (where we re-worked 100 boards).   Only in recent units do we run the Pi4 at 5.1 V.    

On your robot measure with voltmeter steady state voltage just sitting there from ground to  MAIN  5V.  If it is under or at 5.0V then this is known issue and we don't care but you may want to rework that robot, I have a doc for that.

**Comment by JanezCim** [comment]
Did some more tests on this. 
Even without rpi, the robot is acting wierdly:
https://workdrive.zoho.com/file/q89u296e0a34aae914358be67449820f2bd14

And with RPI but without the sd card, the rpi is rotating one wheel until it looses power
https://workdrive.zoho.com/file/q89u28464e3c563d541d18717a189a3a060ba

Between MAIN 5V and GND the voltage reaches 4.9V untill the wheels suddenly stop - then drops down to zero and repeats this in cycles.

**Comment by JanezCim** [comment]
@mjstn any opinion about this?

**Comment by JanezCim** [comment]
marks comment out of chat:

> I would like to know if this issue exists with MCB rev 5.3 and our most recent Production image that loads rev v43 firmware. I am a HUGE believer in getting current production stuff to be ok and only THEN move on to perhaps archaic software leading to issues. the old firmware load default was IMHO crap. It loaded a very poor firmware rev that was something like rev v39 although I don’t recall exactly. A great many things have been fixed since then with the very recent firmware production load that uses v43.

> The current official production firmware loading rev is from date Dec 2, 2021. That should load fw v43. Can you have somebody test and see if THAT is ok or not for this driving in circles??

My answer: 
I have not checked if the board is really 5.3, i just assumed it it is. Have to check it again. And which image is loaded on rpi is irrelevant here since the rpi is not even being turned on as you can see from the first video. So there must be something wrong with hardware

**Comment by JanezCim** [comment]
I've just checked, the MCB revision is indeed 5.3

**Comment by markologic** [comment]
This looks like the defect we reworked boards to avoid.   See if you still have the diodes and do not have the modified resistor in the doc I attach now. 
[MCB_Rework_20210903.docx](https://github.com/UbiquityRobotics/pi_image_build/files/8478224/MCB_Rework_20210903.docx)

**Comment by markologic** [comment]
If not above you should replace the mcb and send the broken one to me or chuck it.   There is some chance it is a 'real' issue that may happen again or it may be a waste of time.   Flip a coin.

**Comment by JanezCim** [comment]
This magni has been given at the end to Andreja - our cardboard box manufacturer for drop testing. This means that the robot has all kinds of dents and unstraight wheels, and who knows what has happened to the mcb inside. So i think we can safely close this since we arent going to be fixing that robot any time soon
