### ISSUE TITLE
mcp7940x RTC

### ISSUE THREAD

**Issue by antoan** [UbiquityRobotics/pi_image_build#4]
Many thanks for your image, I really appreciate it.

I was curious about what made you choose that particular RTC device and if it has anything to do with eliminating problems like RTC corruption.

Cheers,

Antoan

**Comment by rohbotics** [comment]
@waynegramlich I seem to recall that you picked the RTC, so if you have any reasoning to share it would be useful.

As far as I know we picked it because it was one of the ones supported by the raspberry pi kernel that we were using back when we selected it :)

**Comment by waynegramlich** [comment]
All:

I think we picked one that exactly matched one that somebody had already done for Raspberry Pi
daughter board (Ada Fruit?).  We were trying NOT to innovate in the RTC department.  As to
which daughter board it was, alas, I have no recollection.

Regards,

-Wayne

**Comment by antoan** [comment]
Thanks.
